name: CI

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest ./tests/test.py
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: poetry install --no-root --no-dev
      - name: Build distribution package
        run: poetry build
      - name: Upload distribution package
        uses: actions/upload-artifact@v2
        with:
          name: distribution-package
          path: dist/*
