name: CI

on: [push]
jobs:
  test:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    container: ahahaha2333/faster_grad_cam:v4.0
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          poetry env list
  build:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    container: ahahaha2333/faster_grad_cam:v4.0
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build distribution package
        run: |
          poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: upload package
          path: dist/
