name: test_CI

on:
  push:
    branches: [ "dev" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install poetry && poetry install --no-root
      - name: Run tests
        run: poetry run pytest
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install poetry && poetry install --no-root --no-dev
      - name: Build distribution package
        run: poetry build
      - name: Upload distribution package
        uses: actions/upload-artifact@v3
        with:
          name: distribution-package
          path: dist/*
