name: Python Package using Conda

on:
  push:
    branches:
     -dev

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Add conda to system path
      run: |
       echo test CI
